# Site settings
title: John Cipponeri
email: john.cipponeri@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: John Cipponeri
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/johncipponeri
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/users/4380308/john-cipponeri
  - title: bitbucket 
    url: 
  - title: github
    url: http://github.com/johncipponeri

# Postal address (add as many lines as necessary)
address:
  - line: 5605 Winner Road
  - line: Kansas City, MO 64127
  
# Credits content
credits: 'Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
