# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Let's make a Game!
tagline:          'by John Cipponeri'
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://lanyon.getpoole.com

author:
  name:           'John Cipponeri'
  url:            https://twitter.com/johncipponeri

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/johncipponeri/johncipponeri.github.io
